version: '3'
services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
