name: Publish production
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: -- Step 1 -- Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: -- Step 2 -- Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: -- Step 3 -- Install dependencies
        run: yarn install
      - name: -- Step 4 -- Build js
        run: yarn build
      - name: -- Step 5 -- Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: -- Step 6 -- Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: -- Step 7 -- Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: -- Step 8 -- Get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: -- Step 9 -- Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tooot/push:latest,tooot/push:${{ steps.package-version.outputs.current-version}}
